### ISSUE TITLE
compiles with error

### ISSUE THREAD

**Issue by 0x433** [kiffie/pic32-rs-oled-demo#1]
Hi!
It's me again :)

With default build.sh
```
RUST_TARGET_PATH=$(pwd) \
	xargo objcopy --bin oled-test --release -- -O ihex oled-test.hex
```
I have:
```
...
   Compiling pic32-hal v0.1.0 (https://github.com/kiffie/pic32-rs.git#2b176e75)
   Compiling oled-test v0.2.0 (D:\pic32\pic32-rs-oled-demo)
error: could not compile `oled-test`.

To learn more, run the command again with --verbose.
error: Failed to parse crate metadata
```
Adding the --verbose parameter did not clarify anything.

With alternative build command from build.sh :
`RUST_TARGET_PATH=$(pwd) xargo build --target mipsel-none --release`
I have
```
...
   Compiling pic32-hal v0.1.0 (https://github.com/kiffie/pic32-rs.git#2b176e75)
   Compiling oled-test v0.2.0 (D:\pic32\pic32-rs-oled-demo)
error: linking with `rust-lld` failed: exit code: 1
...
  = note: rust-lld: error: link.x:1: unexpected EOF
          >>> 32MX150F128B_procdefs.ld
          >>> ^
```
 I try it from `bash` under Windows only but at the same time examples from `pic32-rs` project are built without errors.

**Comment by kiffie** [comment]
Please try the version of the OLED demo included in the  `pic32-rs` repo, which I could compile under Windows.
